// Style philosophy: adventure is a readable sequence of kingdoms and boss decisions, not a decorative card grid.
import { ArrowUpLeft, Check, ChevronLeft, Compass, Crown, Heart, LockKeyhole, MapPin, Sparkles, Zap } from "lucide-react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { NexusShell, SectionKicker, SignalTrace } from "@/components/nexus/NexusShell";
import { loadProgress } from "@/game/storage";

const kingdoms = [
  { id: 1, number: "01", name: "قرية الإشارة", type: "الأنماط", boss: "حارس التكرار", detail: "رؤية الإشارة قبل أن تتحرك." },
  { id: 2, number: "02", name: "غابة الاستنتاج", type: "المنطق", boss: "سيدة البرهان", detail: "أربع عقد تفصل الحقيقة عن الانطباع." },
  { id: 3, number: "03", name: "جبل اللغة", type: "المفردات", boss: "راوي الظلال", detail: "اختبر دقة العبارة قبل أن تثق بها." },
  { id: 4, number: "04", name: "كهف الاحتمال", type: "الحساب", boss: "ناسج الاحتمال", detail: "وازن بين المسارات ولا تراهن على الانطباع." },
  { id: 5, number: "05", name: "مدينة الذهب", type: "التركيز", boss: "حارس المدينة", detail: "القرار الأخير يحتاج عقلًا هادئًا." },
];

export default function Adventure() {
  const [, setLocation] = useLocation();
  const progress = loadProgress();
  const active = kingdoms.find((kingdom) => !progress.completedStages.includes(kingdom.id) && kingdom.id <= progress.unlockedStages) ?? kingdoms[kingdoms.length - 1];
  const isUnlocked = (id: number) => id <= progress.unlockedStages;
  return <NexusShell><section className="adventure-page"><div className="adventure-intro"><SectionKicker icon={Compass}>B / 05 · ممالك الأطلس</SectionKicker><h1>كل مملكة تغيّر<br /><em>طريقة النظر.</em></h1><p>خمس ممالك مترابطة؛ تنهي كل واحدة في مواجهة حارس معرفي وتكسب طاقة وذهبًا ومسارًا جديدًا.</p><SignalTrace label="حالة الأطلس" value={`${String(progress.completedStages.length).padStart(2, "0")} / 05 · ${active.name}`} /><div className="adventure-intro__meta"><span><MapPin size={15} /> المملكة الحالية <b>{active.number} / 05</b></span><span><Heart size={15} /> القلوب <b>{progress.hearts} / 3</b></span><span><Zap size={15} /> الطاقة <b>{progress.energy} / 5</b></span></div></div><div className="adventure-map panel-surface"><div className="atlas-grid" aria-hidden="true" /><div className="map-label"><span className="eyebrow">NEXUS / KINGDOMS</span><strong>{active.name}</strong><span>الحارس: {active.boss}</span></div><div className="map-route" aria-label="خريطة ممالك المغامرة">{kingdoms.map((kingdom, index) => { const done = progress.completedStages.includes(kingdom.id); const unlocked = isUnlocked(kingdom.id); const status = done ? "complete" : unlocked ? "active" : "locked"; return <button key={kingdom.id} type="button" className={`map-node map-node--${status}`} onClick={() => unlocked && setLocation(`/play?mode=adventure&stage=${kingdom.id}`)}><span className="map-node__number">{done ? <Check size={15} /> : !unlocked ? <LockKeyhole size={14} /> : kingdom.number}</span><span className="map-node__name">{kingdom.name}</span><small>{kingdom.type}</small>{index < kingdoms.length - 1 && <i className="map-node__connector" />}</button>; })}</div><div className="map-coordinate">N 02° 04′<br />E 16° 09′</div></div><div className="adventure-stages"><div className="section-heading"><div><span className="eyebrow">الممالك والحراس</span><h2>اختر معركة أثر.</h2></div><span className="heading-note">{progress.completedStages.length} مكتملة</span></div>{kingdoms.map((kingdom) => { const done = progress.completedStages.includes(kingdom.id); const unlocked = isUnlocked(kingdom.id); return <div className={`stage-row stage-row--${done ? "complete" : unlocked ? "active" : "locked"}`} key={kingdom.id}><span className="stage-row__number">{kingdom.number}</span><div className="stage-row__copy"><strong>{kingdom.name} <small>· {kingdom.boss}</small></strong><span>{kingdom.detail}</span></div><span className="stage-row__type">{kingdom.type}</span>{done ? <span className="stage-done"><Check size={14} /> هُزم الحارس</span> : unlocked ? <Button size="sm" className="signal-button signal-button--small" onClick={() => setLocation(`/play?mode=adventure&stage=${kingdom.id}`)}><Crown size={14} /> مواجهة <ArrowUpLeft size={14} /></Button> : <LockKeyhole size={15} className="stage-lock" />}</div>; })}</div><Link href="/" className="text-link adventure-back"><ChevronLeft size={15} /> العودة إلى المركز</Link></section></NexusShell>;
}
